AllCops:
  Exclude:
    - 'feiku.gemspec'
    - 'vendor/**/*'
  NewCops: enable
  TargetRubyVersion: 3.0

Metrics:
  Exclude:
    - 'test/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
